// b2b/003-01-admin/apps/admin/admin-frontend/src/features/auth/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';

import { AuthService } from '../../core/auth.service';

@Component({
  standalone: true,
  selector: 'admin-login',
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
  <div class="card">
    <h2>Sign in</h2>
    <p>Demo account: <code>admin@admin</code> / <code>admin</code></p>
    <form (ngSubmit)="submit()">
      <input [(ngModel)]="email" name="email" type="email" placeholder="Email" required>
      <input [(ngModel)]="password" name="password" type="password" placeholder="Password" required>
      <button type="submit">Sign in</button>
    </form>
    <p><a routerLink="/forgot">Forgot password?</a></p>
    <div class="err" *ngIf="error">Invalid credentials.</div>
  </div>`,
  styles: [`
  .card{max-width:420px;margin:10vh auto;background:#ffffff;border:1px solid #e5e7eb;border-radius:14px;padding:1.2rem;color:#0f172a}
  .err{color:#b91c1c;margin-top:.6rem}
  .ok{color:#047857;margin:.6rem 0}
`]
})
export class LoginComponent {
  email = ''; password = ''; error = false;

  constructor(private auth: AuthService, private router: Router) { }

  async submit() {
    this.error = false;
    try { await this.auth.login(this.email, this.password); this.router.navigateByUrl('/'); }
    catch { this.error = true; }
  }
}

// b2c/003-01-admin/apps/admin-frontend/pages/login.vue
<template>
  <div class="auth">
    <h1>Sign in</h1>
    <form @submit.prevent="submit">
      <input v-model="login" placeholder="Email or login" required />
      <input v-model="password" type="password" placeholder="Password" required />
      <button type="submit">Sign in</button>
    </form>
    <NuxtLink to="/forgot-password">Forgot password?</NuxtLink>
  </div>
</template>

<script setup lang="ts">
import { useAuthStore } from '@/stores/auth';
const store = useAuthStore();
const login = ref('test');
const password = ref('test');
const submit = async () => {
  await store.login(login.value, password.value);
  await navigateTo('/');
};
</script>

<style scoped>
.auth {
  max-width: 360px;
  margin: 10vh auto;
  background: white;
  padding: 1.25rem;
  border-radius: 12px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, .05)
}

.auth input {
  width: 100%;
  margin: .5rem 0;
  padding: .6rem;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.auth button {
  width: 100%;
  padding: .6rem;
  border: none;
  border-radius: 8px;
  background: #111;
  color: white;
}
</style>
