// b2c/001-02-foundations/apps/web-frontend/app/page.tsx
export default async function Home() {
  const base = process.env.INTERNAL_WEB_API_URL || 'http://web-api:3000';
  const res = await fetch(`${base}/status`, { cache: 'no-store' });
  const data = await res.text();
  return (
    <main className="min-h-screen grid place-items-center">
      <div className="p-6 rounded-xl shadow bg-white">
        <h1 className="text-2xl font-bold">B2C Frontend</h1>
        <p className="mt-2 text-gray-600">API says:</p>
        <p className="mt-4 font-mono">{data}</p>
      </div>
    </main>
  );
}

// b2c/003-01-admin/apps/admin-frontend/app.vue
<template>
  <main class="min-h-screen grid place-items-center">
    <div class="p-6 rounded-xl shadow bg-white">
      <h1 class="text-2xl font-bold">Admin Frontend</h1>
      <p class="mt-2 text-gray-600">API says:</p>
      <p class="mt-4 font-mono">{{ status }}</p>
    </div>
  </main>
</template>


<script setup lang="ts">
const config = useRuntimeConfig();
const base = config.INTERNAL_ADMIN_API_URL as string;
const { data, error } = await useFetch<string>(`${base}/status`, { server: true });
const status = data.value ?? (error.value ? 'N/A' : '');
</script>


<style>
/* Tailwind optionnel dans une étape suivante */
</style>
